export const GET_GRAPH_REQUEST = 'GET_GRAPH_REQUEST';
export const GET_GRAPH_SUCCESS = 'GET_GRAPH_SUCCESS';
export const GET_GRAPH_FAILURE = 'GET_GRAPH_FAILURE';

export const GET_STATUS_REQUEST = 'GET_STATUS_REQUEST';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE';

export const SELECT_NODE = 'SELECT_NODE';
export const TOGGLE_PANEL = 'TOGGLE_PANEL';
