export const GET_GRAPH_REQUEST = 'GET_GRAPH_REQUEST';
export const GET_GRAPH_SUCCESS = 'GET_GRAPH_SUCCESS';
export const GET_GRAPH_FAILURE = 'GET_GRAPH_FAILURE';

export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAILURE = 'GET_DETAILS_FAILURE';

export const SELECT_NODE = 'SELECT_NODE';
export const TOGGLE_PANEL = 'TOGGLE_PANEL';

export const SET_FILTER = 'SET_FILTER';
export const ADD_FILTER = 'ADD_FILTER';
export const SET_GROUP_LEVEL = 'SET_GROUP_LEVEL';
export const SELECT_GROUP = 'SELECT_GROUP';
export const SET_NEIGHBOUR_LEVEL = 'SET_NEIGHBOUR_LEVEL';
